### ISSUE TITLE
OverflowError

### ISSUE THREAD

**Issue by York1996OutLook** [RonTang/HackerTutorial#1]
DLL路径：C:\Users\qqyor\source\repos\Dll1\Debug\Dll1.dll,目标进程：肉鸭.exe
发现名为肉鸭.exe的进程,进程id:19372
向目标进程写入94字节成功
Traceback (most recent call last):
  File "E:/python/socket/remoteThreadInject.py", line 146, in injectSlot
    injectDll(self.lineEdit_2.text(), self.lineEdit.text())
  File "E:/python/socket/remoteThreadInject.py", line 75, in injectDll
    handle = kernel32.CreateRemoteThread(h_process, None, 0, h_loadlib, arg_adress, 0, byref(thread_id))
ctypes.ArgumentError: argument 4: <class 'OverflowError'>: int too long to convert

**Comment by RonTang** [comment]
您注意一下32位 和 64位程序是不是混用了
